export enum PromptTypeEnum {
  INSTRUCTIONS = 'INSTRUCTIONS',
  TEXT_STYLE = 'TEXT_STYLE',
  TEXT_TONE = 'TEXT_TONE',
  REACTION_TYPE = 'REACTION_TYPE',
  COMMENT_LENGTH = 'COMMENT_LENGTH',
  CONTEXT = 'CONTEXT',
}
